### ISSUE TITLE
gcl breaks/expands tabs in strings

### ISSUE THREAD

**Issue by spinus** [rix0rrr/gcl#16]
```
x = "     ";  # inside there is one tab, \t
```

when in python it is expanded to 8 spaces I think.
It should not expand tabs I guess.

**Comment by spinus** [comment]
I found the problem is inside pyparsing.

In `ParseElement` class there is a switch `keepTabs` which is defaulted to `False` but I don't see how to switch this in gcl.

In `ParseElement` there is also `copyDefaultWhitespace` (set to `True`) and white space char list set to "\n\t\r" but does not work either (I didn't spend too much time there).

Possible quickfix would be to set `keepTabs=True` before `parseString` in `reads` function in `gcl/__init__.py` file.

**Comment by rix0rrr** [comment]
Got fixed in 3b82846.

**Comment by spinus** [comment]
+1 Thank you
