### ISSUE TITLE
" and ' escaping does not work inside a string

### ISSUE THREAD

**Issue by spinus** [rix0rrr/gcl#17]
```
x = " hello \"world\" ";
```

is invalid, looks like \ is omitted. \" doesn't work either. Same for '.

**Comment by rix0rrr** [comment]
Well, isn't that the point of escaping? If you want to embed a literal double quote inside a double quoted string?

I added a unit test to verify that quote escaping does work as intended.

**Comment by spinus** [comment]
OK, so I need to escape backslash as well. I see. I thought that \" will be enough to escape ".
Thank you for explaining.
