### ISSUE TITLE
Problem with values inheritance.

### ISSUE THREAD

**Issue by spinus** [rix0rrr/gcl#18]
case1:

```
zz = {
  package = {
      package-name = "hoho";
        rules = {};
    };
    rule1 = {
      rule-name = "bla";
    };
};

my_pkg = zz.package {
  rules = base.rules {
      my-rule = zz.rule1 {
          inherit rule-name;
          inherit package-name;
            some-var2 = package-name;
            some-var = rule-name;
        }
    }
};
```

case2:

```
```

I have this situation, `some-var` and `some-var2` cannot be evaluated due to `Unbound variable: 'package-name'` and the same for `rule-name`.

I think I'm not fully understand how this inheritance should work, could you please explain or give a clue?

**Comment by rix0rrr** [comment]
Hi Tomek,

`inherit` exists for exactly one purpose: to COPY a variable from an outer scope into a tuple with the same name. So, you'd only want to use `inherit` in a case like this:

```
x = 3;
foo = {
    # I MUST have a key with the name 'x' here
    inherit x;
}
```

If you want to rename the variable, you can simply assign it:

```
x = 3;
foo = {
    y = x;
}
```

In your case, the thing you're trying to inherit is not available from an outer scope. It IS however in the parent scope of a tuple you're compositing with, but you have to bring it into the scope of your local tuple, like so:

```
my_pkg = zz.package {
package-name;
rules = base.rules {
    my-rule = zz.rule1 {
            rule-name;
            some-var2 = package-name;
            some-var = rule-name;
        }
    }
};
```

**Comment by spinus** [comment]
This works perfectly thank you.
I was confused by using "package-name" in the form you used here, I thought that it's only for variable declaration, but not for making it visible (that's why I tried inherit, which was wrong).

**Comment by spinus** [comment]
Hey @rix0rrr, what do you think about making those two actions different?
Declaring the value or "inheriting" it from parent?
I assume this could always go the explicit route like

```
x = y {
  q = base.q;  # get from parent
  z;  # declare
};
```

or maybe with some sugar:

```
x = y {
  get q;
  <q>;
  @q;
  z;
};
```

**Comment by rix0rrr** [comment]
Actually, just writing the variable name is already enough to import it from the "parent".

```
x = y {
  q;
  z = q + 1;
}
```

**Comment by spinus** [comment]
Maybe I was not very precise. I know, but the same way you declare a variable.

for example

```
foo = something {
  x;
};
```

You don't know here if x was defined or was "fetched" from the parent. And this makes the difference, because if it was defined, current foo model is complete. But if x wasn't defined in "something" this will be an error that x has no value and must be overridden.

What I'm suggesting is to make a different operators for those two operations to avoid that situation.
