### ISSUE TITLE
Shortcut for extending values?

### ISSUE THREAD

**Issue by spinus** [rix0rrr/gcl#19]
Currently to extend a variable you need to use "base", like:

```
my-var = base.my-var + [1,2,3];
```

Maybe some shortcut would be suitable here, let's say:

```
my-var += [1,2,3];
```

or

```
my-var ++ [1,2,3];
```

**Comment by rix0rrr** [comment]
Hmmm. This makes GCL seem very imperative, which I'm not too fond of. I'll think about it.

**Comment by spinus** [comment]
so maybe

```
my-var = base.$ + [1,2,3];
```

(or whatever else instead of $)

**Comment by rix0rrr** [comment]
Can you explain the use case a bit more?

What and how are you building the models such that you need to do array concatenation so much? Maybe there is another way to structure your tuples so that this isn't necessary.

**Comment by spinus** [comment]
```
service-base {
  dependencies = ["standard dependency1", "standard dependency2"];
};
services = {
  service1 = base.service-base {
     dependencies = base.dependencies + ["something else"];
  };
  # lots of services here
};
```
