### ISSUE TITLE
A string substitution

### ISSUE THREAD

**Issue by orian** [rix0rrr/gcl#21]
Would be cool to have a string substitution:

``````
{
 host = "x"
 port = 1234
 address = "%host%:%port%"
}```

In fact just concatenating string with numbers would be fine.
``````

**Comment by rix0rrr** [comment]
We actually have that, by means of the `fmt` function. This functions takes two arguments:

```
fmt(string, [environment])
```

If you leave out the second argument (which then defaults to the "current" environment), you can leave out the parens:

```
fmt 'string'
```

And would be used in a more complex example like so:

```
{
    host = 'x';
    port = 1234;
    address = fmt '{host}:{port}';
}
```

**Comment by orian** [comment]
That's super cool, what about adding a bit of info into the doc? I guess here is the list of build-in functions: https://github.com/rix0rrr/gcl/blob/master/gcl/functions.py#L75
