### ISSUE TITLE
Injecting values from Python script doesn't work as I expected?

### ISSUE THREAD

**Issue by joshburkart** [rix0rrr/gcl#25]
This:

``` python
gcl.loads('a;', env={'a': 6})['a']
```

raises `EvaluationError: <input>:1: Unbound value: 'a' in 'a;'`. I was expecting it to return `6`. Am I misunderstanding how this is supposed to work?

**Comment by cosu** [comment]
try this 

``` python
>>> gcl.loads('a', implicit_tuple=False, env={'a':6})
6
```

**Comment by joshburkart** [comment]
Ahh ok, so `env` only injects 'global' variables. It would be nice to be able to inject things at any level, but I guess I can do that with tuple composition? Thanks!

**Comment by rix0rrr** [comment]
Yeah, what you pass in in `env` is the "outermost" environment of your evaluation. Thanks for explaining @cosu!
