### ISSUE TITLE
Schema definition inside the model

### ISSUE THREAD

**Issue by rix0rrr** [rix0rrr/gcl#4]
See AWS policies, I want to be able to ignore all the extraneous crap.

**Comment by pjjw** [comment]
+1. using selectors and shunt python to get around this at the moment, but yeah.

**Comment by rix0rrr** [comment]
A module that's available (but unfortunately undocumented as of yet) is `gcl.query`, which allows you to do something like this:

```
policy_query = gcl.query.GPath([
    'Version',
    'Id',
    'Statement.*.{Sid, Condition, Action, Resource, Effect, Principal}',
])

policy = policy_query.select(policy_tuple).deep()
return gcl.util.to_python(policy)
```

**Comment by rix0rrr** [comment]
We finally got schemas!
