### ISSUE TITLE
Support foo.bar.baz syntax

### ISSUE THREAD

**Issue by rix0rrr** [rix0rrr/gcl#9]
For compatibility with another (unnamed) language

**Comment by spinus** [comment]
+1

**Comment by spinus** [comment]
This should be pretty easy to do with
https://pypi.python.org/pypi/bunch/1.0.1 or https://pypi.python.org/pypi/neobunch/2.0.0
Probably it's just enough to wrap dict object, right?

**Comment by rix0rrr** [comment]
Y'know what... I'm never going to do this. Closing.
